[db]
jdbc.driver=oracle.jdbc.OracleDriver
jdbc.url=jdbc\:oracle\:thin\:@localhost\:1521\:ORCL
jdbc.user=gcc2
jdbc.password=gcc2
jdbc.validationQuery=select 'x' from dual
jdbc.decrypt=false
jdbc.initialSize=100
jdbc.minIdle=50
jdbc.maxActive=220

#shiro
password.algorithmName=SHA-256
password.hashIterations=3

student =/exam
filepath=E:/xunfei/exam_upload_files/
wj_cid=1444

projectName=smuexamgc

graphicsMagickPath=F:/develop/GraphicsMagick-1.3.45-Q16/GraphicsMagick-1.3.45-Q16/
latexToSVGNodePath=F:/NodeJs/

#是否启用查重系统，0是关闭，1是开启，开启后会记录试卷被操作后的数据将用于同步eid至查重服务器
openFindRepeatSystem=0
#查重服务器的ip和端口或域名，要以http://或https://开头，目前没有后缀，如果有后缀不要以“/”结尾
stats.baseUrl=http://localhost:8085
#用于查重服务器鉴定权限，固定值
stats.apiKey=AK-rEqewx0uXa4fFHPuuVEQ3sSF7B5PlRVnEfkT